const TOKEN_KEY='jsm_tokens';const VW_KEY='jsm_vw';
function getT(){try{return parseInt(localStorage.getItem(TOKEN_KEY)||'0',10);}catch(_){return 0;}}
function addT(n){const t=getT()+n;try{localStorage.setItem(TOKEN_KEY,t);}catch(_){}document.querySelectorAll('.js-token-count').forEach(el=>el.textContent=t);}
function initHam(){const b=document.getElementById('hamburger-btn'),m=document.getElementById('nav-menu'),o=document.getElementById('nav-overlay');if(!b||!m)return;const op=()=>{b.classList.add('open');m.classList.add('open');if(o)o.classList.add('open');document.body.style.overflow='hidden';};const cl=()=>{b.classList.remove('open');m.classList.remove('open');if(o)o.classList.remove('open');document.body.style.overflow='';};b.addEventListener('click',()=>m.classList.contains('open')?cl():op());if(o)o.addEventListener('click',cl);document.addEventListener('keydown',e=>{if(e.key==='Escape')cl();});const p=location.pathname.split('/').pop()||'index.html';m.querySelectorAll('a').forEach(a=>{if(a.getAttribute('href')===p)a.classList.add('active');});}
const VIDS=[
  {id:'p5oUI7RCyUI',title:'Mechanics & Motion',topic:'Mechanics',desc:"Miller opens with forces, mass and Newton's Laws. He yanks a tablecloth from under dishes to prove inertia. The most dramatic intro to physics ever filmed."},
  {id:'j-ixGKZlgKo',title:'Gravity & Free Fall',topic:'Gravity',desc:'All objects fall at 9.8 m/s² regardless of mass. Miller proved Galileo right on television. Aristotle was wrong for 2,000 years. Why is it so?'},
  {id:'hmFQqjMF_f0',title:'Pendulums & Oscillation',topic:'Oscillation',desc:"A pendulum's period depends ONLY on length — not mass, not angle. Miller sets up pendulums of every size. Predict the result, then see the truth."},
  {id:'pMbWrPYCpDw',title:'Pressure & Fluids',topic:'Fluids',desc:"Miller seals a can of steam, cools it — the atmosphere crushes it flat. 10 tonnes per square metre of invisible force made visible."},
  {id:'KPZ_8pL_a_g',title:'Heat & Temperature',topic:'Thermodynamics',desc:'Heat and temperature are NOT the same thing. The fire syringe, thermal expansion, liquid nitrogen — adiabatic compression explained with drama.'},
  {id:'RVsi2DM1xbU',title:'Electricity & Magnetism',topic:'Electromagnetism',desc:"The Van de Graaff builds hundreds of thousands of volts. Hair stands on end. Sparks fly. Faraday's laws made visceral."},
  {id:'sENgdSF8ppA',title:'Light & Optics',topic:'Optics',desc:"White light through a prism — Newton's rainbow. Total internal reflection. The eye, telescope and camera all use identical principles."},
  {id:'zQ1sMhFDjNE',title:'Sound & Waves',topic:'Waves',desc:'A bell rings in a glass jar. Miller pumps out the air — sound fades to silence. There is no sound in space. The universe has rules.'},
  {id:'BLEiE-TdNNQ',title:'Inertia Demonstrations',topic:'Inertia',desc:"Tablecloth yanked from under dishes. Cards snapped from under coins. A body at rest stays at rest. The universe is lazy — that is the law."},
  {id:'vFfninh2Zbk',title:'Surface Tension',topic:'Surface Tension',desc:'A steel needle floats on water. Molecular forces create an elastic surface skin. Miller adds one drop of soap — the needle sinks instantly.'},
  {id:'D-LQeWREUVs',title:'The Gyroscope',topic:'Angular Momentum',desc:'A spinning gyroscope defies gravity and resists changes to its axis. Angular momentum is conserved. The physics that navigates ships and satellites.'},
  {id:'Wb7eDXbhLco',title:'Atmospheric Pressure',topic:'Pressure',desc:'The atmosphere weighs 10+ tonnes per square metre on everything beneath it. Miller makes this invisible giant crush, lift, and bend metal.'},
];
function initPlaylist(){
  const fr=document.getElementById('main-player'),gr=document.getElementById('playlist-grid'),tEl=document.getElementById('video-title'),tpEl=document.getElementById('video-topic'),dEl=document.getElementById('video-desc');
  if(!fr||!gr)return;
  function load(i){const v=VIDS[i];fr.src='https://www.youtube.com/embed/'+v.id+'?autoplay=1&rel=0&modestbranding=1';if(tEl)tEl.textContent=v.title;if(tpEl)tpEl.textContent=v.topic;if(dEl)dEl.textContent=v.desc;gr.querySelectorAll('.playlist-item').forEach((e,j)=>e.classList.toggle('active',j===i));let w=[];try{w=JSON.parse(sessionStorage.getItem(VW_KEY)||'[]');}catch(_){}if(!w.includes(v.id)){w.push(v.id);try{sessionStorage.setItem(VW_KEY,JSON.stringify(w));}catch(_){}addT(2);toast('🏅 +2 tokens!');}}
  VIDS.forEach((v,i)=>{const d=document.createElement('div');d.className='playlist-item'+(i===0?' active':'');d.innerHTML='<div class="playlist-thumb"><img src="https://img.youtube.com/vi/'+v.id+'/mqdefault.jpg" alt="'+v.title+'" loading="lazy" onerror="this.parentNode.innerHTML=\'<div style=background:#111;width:100%;height:100%;display:flex;align-items:center;justify-content:center;color:#555>▶</div>\'"><div class="play-icon">▶</div></div><div style="padding:.4rem .5rem"><div class="playlist-title">'+v.title+'</div><div style="font-size:.65rem;color:var(--accent);font-weight:700;text-transform:uppercase;margin:.15rem 0">'+v.topic+'</div><div style="font-size:.65rem;color:#777;line-height:1.3">'+v.desc.substring(0,80)+'...</div></div>';d.addEventListener('click',()=>load(i));gr.appendChild(d);});
  if(tEl)tEl.textContent=VIDS[0].title;if(tpEl)tpEl.textContent=VIDS[0].topic;if(dEl)dEl.textContent=VIDS[0].desc;
  fr.src='https://www.youtube.com/embed/'+VIDS[0].id+'?rel=0&modestbranding=1';
}
function toast(m){let t=document.getElementById('jsm-toast');if(!t){t=document.createElement('div');t.id='jsm-toast';t.style.cssText='position:fixed;bottom:1.5rem;left:50%;transform:translateX(-50%) translateY(60px);background:#1a1a2e;border:1px solid var(--accent);border-radius:8px;padding:.6rem 1.2rem;color:var(--accent);font-size:.85rem;z-index:900;transition:transform .3s;white-space:nowrap;';document.body.appendChild(t);}t.textContent=m;t.style.transform='translateX(-50%) translateY(0)';clearTimeout(t._t);t._t=setTimeout(()=>t.style.transform='translateX(-50%) translateY(60px)',2200);}
const QQ=[{q:"Miller's famous TV series?",opts:['Why Is It So?','The Physics Show','Science Matters','Matter & Energy'],a:0,e:'"Why Is It So?" — his iconic phrase and ABC series from 1963.'},{q:"Newton's First Law: object stays at rest unless:",opts:['Gravity acts','Unbalanced force acts','Friction acts','Weight changes'],a:1,e:"An unbalanced external force is required to change state of motion."},{q:'Dropped ball acceleration (no air):',opts:['Zero','Decreasing','Constant 9.8 m/s²','Variable'],a:2,e:'Gravity provides constant 9.8 m/s² downward.'},{q:"Bernoulli's Principle:",opts:['Faster fluid = higher pressure','Faster fluid = lower pressure','Pressure constant','Fluids flow downhill'],a:1,e:'Where velocity is higher, pressure is lower.'},{q:"Why do boats float?",opts:["Newton's 3rd","Boyle's Law","Archimedes' Principle","Ohm's Law"],a:2,e:"A submerged object is buoyed by a force equal to the weight of fluid displaced."},{q:'Skater pulls arms in:',opts:['Slows down','Speeds up','Falls','No change'],a:1,e:'Less moment of inertia → faster spin to conserve angular momentum.'},{q:'Sound fastest in:',opts:['Vacuum','Air','Water','Steel'],a:3,e:'Steel ~5100 m/s, water ~1480 m/s, air ~343 m/s, vacuum = 0.'},{q:'F = ma:',opts:['Force=mass+accel','Force=mass×accel','Force=9.8','Friction=mass×area'],a:1,e:"Newton's Second Law: Force = mass × acceleration."},];
let qi=0,qs=0;
function initQuiz(){if(document.getElementById('quiz-container'))renderQ();}
function renderQ(){const c=document.getElementById('quiz-container');if(!c)return;if(qi>=QQ.length){c.innerHTML='<div style="text-align:center;padding:2rem"><p style="font-size:3rem">🏅</p><h3>Quiz Complete!</h3><p>Score: <strong>'+qs+'/'+QQ.length+'</strong> · Tokens: <strong>+'+(qs*5)+'</strong></p><button onclick="location.reload()" style="margin-top:1rem;padding:.6rem 1.5rem;background:var(--accent);color:#fff;border:none;border-radius:8px;cursor:pointer">Try Again</button></div>';addT(qs*5);return;}const q=QQ[qi];c.innerHTML='<p style="font-size:.82rem;color:var(--text-secondary);margin-bottom:.5rem">Q'+(qi+1)+' of '+QQ.length+'</p><p style="font-weight:700;margin-bottom:1rem">'+q.q+'</p><div style="display:flex;flex-direction:column;gap:.5rem">'+q.opts.map((o,i)=>'<button onclick="ansQ('+i+')" style="text-align:left;padding:.7rem 1rem;background:var(--bg-card);border:1px solid var(--border);border-radius:8px;cursor:pointer;color:var(--text-primary)">'+o+'</button>').join('')+'</div>';}
function ansQ(i){const q=QQ[qi];const ok=i===q.a;if(ok)qs++;document.getElementById('quiz-container').innerHTML='<div style="padding:1.2rem;background:'+(ok?'rgba(0,200,100,.08)':'rgba(255,60,60,.08)')+';border:1px solid '+(ok?'#00c864':'#ff3c3c')+';border-radius:10px;margin-bottom:1rem">'+(ok?'✅ Correct!':'❌ Not quite')+'<p style="font-size:.88rem;margin-top:.5rem;line-height:1.5">'+q.e+'</p></div><button onclick="nxtQ()" style="padding:.6rem 1.5rem;background:var(--accent);color:#fff;border:none;border-radius:8px;cursor:pointer">Next →</button>';}
function nxtQ(){qi++;renderQ();}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.js-token-count').forEach(el=>el.textContent=getT());initHam();initPlaylist();initQuiz();});
