const TOKEN_KEY='jsm_tokens';const VIDEO_WATCHED_KEY='jsm_videos_watched';
function getTokens(){try{return parseInt(localStorage.getItem(TOKEN_KEY)||'0',10);}catch(_){return 0;}}
function addTokens(n){const t=getTokens()+n;try{localStorage.setItem(TOKEN_KEY,t);}catch(_){}updateAllTokenDisplays();return t;}
function updateAllTokenDisplays(){const t=getTokens();document.querySelectorAll('.js-token-count').forEach(el=>{el.textContent=t;});}
function initHamburger(){const btn=document.getElementById('hamburger-btn'),menu=document.getElementById('nav-menu'),ov=document.getElementById('nav-overlay');if(!btn||!menu)return;function open(){btn.classList.add('open');menu.classList.add('open');if(ov)ov.classList.add('open');document.body.style.overflow='hidden';}function close(){btn.classList.remove('open');menu.classList.remove('open');if(ov)ov.classList.remove('open');document.body.style.overflow='';}btn.addEventListener('click',()=>menu.classList.contains('open')?close():open());if(ov)ov.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});const path=location.pathname.split('/').pop()||'index.html';menu.querySelectorAll('a').forEach(a=>{if(a.getAttribute('href')===path)a.classList.add('active');});}
const JSM_VIDEOS=[
  {id:'p5oUI7RCyUI',title:'Mechanics & Motion',topic:'Mechanics',desc:"Miller opens with forces, mass and Newton's Laws. He yanks a tablecloth from under dishes to prove inertia. The most dramatic intro to physics ever filmed."},
  {id:'j-ixGKZlgKo',title:'Gravity & Free Fall',topic:'Gravity',desc:'Does a heavy ball fall faster? Miller drops objects of different masses — all fall at 9.8 m/s² regardless. Galileo was right. Aristotle was wrong for 2,000 years.'},
  {id:'hmFQqjMF_f0',title:'Pendulums & Oscillation',topic:'Oscillation',desc:"A pendulum's period depends ONLY on length — not mass, not angle. Miller sets up pendulums of every size. Predict the result, then see the truth."},
  {id:'pMbWrPYCpDw',title:'Pressure & Fluids',topic:'Fluids',desc:"Atmospheric pressure is enormous — we don't feel it because it pushes from all sides. Miller seals a can of steam, cools it, and it's crushed flat."},
  {id:'KPZ_8pL_a_g',title:'Heat & Temperature',topic:'Thermodynamics',desc:'Heat and temperature are NOT the same. The fire syringe, thermal expansion, liquid nitrogen — adiabatic compression and extreme cold explained.'},
  {id:'RVsi2DM1xbU',title:'Electricity & Magnetism',topic:'Electromagnetism',desc:"The Van de Graaff builds hundreds of thousands of volts. Hair stands on end. Sparks fly. Faraday's laws made visceral."},
  {id:'sENgdSF8ppA',title:'Light & Optics',topic:'Optics',desc:"White light through a prism reveals Newton's rainbow. Total internal reflection. The eye, telescope and camera use identical principles."},
  {id:'zQ1sMhFDjNE',title:'Sound & Waves',topic:'Waves',desc:'A bell rings in a glass jar. Miller pumps out the air — the sound fades to silence. There is no sound in space. The universe has rules.'},
  {id:'BLEiE-TdNNQ',title:'Inertia Demonstrations',topic:'Inertia',desc:"Newton's First Law made visceral — tablecloth pulled from under dishes, cards snapped from coins. A body at rest stays at rest. The universe is lazy."},
  {id:'vFfninh2Zbk',title:'Surface Tension',topic:'Surface Tension',desc:'A steel needle floats on water. Molecular forces create an elastic surface skin. Miller adds one drop of soap — the needle sinks instantly.'},
  {id:'D-LQeWREUVs',title:'The Gyroscope',topic:'Angular Momentum',desc:'A spinning gyroscope defies gravity and resists changes to its axis. Angular momentum is conserved. The physics of navigation and satellites.'},
  {id:'Wb7eDXbhLco',title:'Atmospheric Pressure',topic:'Pressure',desc:'The atmosphere weighs 10+ tonnes per square metre on everything. Miller shows how this invisible force can crush metal cans and run hydraulic machines.'},
];
let curVidIdx=0;
function initPlaylist(){
  const iframe=document.getElementById('main-player'),grid=document.getElementById('playlist-grid'),titleEl=document.getElementById('video-title'),topicEl=document.getElementById('video-topic'),descEl=document.getElementById('video-desc');
  if(!iframe||!grid)return;
  function loadVideo(idx){curVidIdx=idx;const v=JSM_VIDEOS[idx];iframe.src='https://www.youtube.com/embed/'+v.id+'?autoplay=1&rel=0&modestbranding=1';if(titleEl)titleEl.textContent=v.title;if(topicEl)topicEl.textContent=v.topic;if(descEl)descEl.textContent=v.desc;grid.querySelectorAll('.playlist-item').forEach((el,i)=>el.classList.toggle('active',i===idx));let w=[];try{w=JSON.parse(sessionStorage.getItem(VIDEO_WATCHED_KEY)||'[]');}catch(_){}if(!w.includes(v.id)){w.push(v.id);try{sessionStorage.setItem(VIDEO_WATCHED_KEY,JSON.stringify(w));}catch(_){}addTokens(2);showToast('🏅 +2 tokens!');}}
  JSM_VIDEOS.forEach((v,i)=>{const item=document.createElement('div');item.className='playlist-item'+(i===0?' active':'');item.innerHTML='<div class="playlist-thumb"><img src="https://img.youtube.com/vi/'+v.id+'/mqdefault.jpg" alt="'+v.title+'" loading="lazy" onerror="this.parentNode.style.background=\'#111\';this.remove();"><div class="play-icon">▶</div></div><div class="playlist-info"><div class="playlist-title">'+v.title+'</div><div class="playlist-topic">'+v.topic+'</div><div class="playlist-desc">'+v.desc.substring(0,85)+'...</div></div>';item.addEventListener('click',()=>loadVideo(i));grid.appendChild(item);});
  const f=JSM_VIDEOS[0];iframe.src='https://www.youtube.com/embed/'+f.id+'?rel=0&modestbranding=1';if(titleEl)titleEl.textContent=f.title;if(topicEl)topicEl.textContent=f.topic;if(descEl)descEl.textContent=f.desc;
}
function showToast(msg){let t=document.getElementById('jsm-toast');if(!t){t=document.createElement('div');t.id='jsm-toast';t.style.cssText='position:fixed;bottom:1.5rem;left:50%;transform:translateX(-50%) translateY(60px);background:#1a1a2e;border:1px solid var(--accent);border-radius:8px;padding:.6rem 1.2rem;color:var(--accent);font-size:.85rem;z-index:900;transition:transform .3s;';document.body.appendChild(t);}t.textContent=msg;t.style.transform='translateX(-50%) translateY(0)';clearTimeout(t._t);t._t=setTimeout(()=>{t.style.transform='translateX(-50%) translateY(60px)';},2400);}
const QQ=[{q:"What was Miller's famous TV series title?",opts:['Why Is It So?','The Physics Show','Science Matters','Matter & Energy'],a:0,e:'"Why Is It So?" — his iconic phrase and ABC series from 1963.'},{q:"Newton's First Law: object stays at rest unless acted on by:",opts:['Gravity','An unbalanced force','Friction only','Its own weight'],a:1,e:"An unbalanced external force is required to change state of motion."},{q:'A dropped ball falls with (no air resistance):',opts:['Zero','Decreasing','Constant 9.8 m/s²','Increasing then decreasing'],a:2,e:'Gravity provides constant 9.8 m/s² downward.'},{q:"Bernoulli's Principle:",opts:['Faster fluid = higher pressure','Faster fluid = lower pressure','Pressure is constant','Fluids flow downhill'],a:1,e:'Where velocity is higher, pressure is lower. This explains flight.'},{q:"Archimedes' Principle explains:",opts:["Newton's 3rd Law","Boyle's Law","Why boats float","Ohm's Law"],a:2,e:"A submerged object is buoyed by a force equal to the weight of fluid displaced."},{q:'Spinning skater pulls arms in:',opts:['Slows down','Speeds up','Falls over','Stays the same'],a:1,e:'Less moment of inertia → faster spin to conserve angular momentum.'},{q:'Sound travels fastest in:',opts:['Vacuum','Air','Water','Steel'],a:3,e:'Steel ~5100 m/s, water ~1480 m/s, air ~343 m/s, vacuum = 0.'},{q:'F = ma means:',opts:['Force = mass + accel','Force = mass × accel','Force = 9.8 always','Friction = mass × area'],a:1,e:"Newton's Second Law: Force = mass × acceleration."},];
let qi=0,qs=0;
function initQuiz(){if(document.getElementById('quiz-container'))renderQ();}
function renderQ(){const c=document.getElementById('quiz-container');if(!c)return;if(qi>=QQ.length){c.innerHTML='<div style="text-align:center;padding:2rem"><div style="font-size:3rem;margin-bottom:1rem">🏅</div><h3>Quiz Complete!</h3><p>Score: <strong>'+qs+'/'+QQ.length+'</strong></p><p>Tokens: <strong>+'+(qs*5)+'</strong> 🏅</p><button onclick="location.reload()" style="margin-top:1rem;padding:.6rem 1.5rem;background:var(--accent);color:#fff;border:none;border-radius:8px;cursor:pointer">Try Again</button></div>';addTokens(qs*5);return;}const q=QQ[qi];c.innerHTML='<div style="margin-bottom:.5rem;font-size:.85rem;color:var(--text-secondary)">Question '+(qi+1)+' of '+QQ.length+'</div><p style="font-size:1.05rem;font-weight:600;margin-bottom:1rem">'+q.q+'</p><div style="display:flex;flex-direction:column;gap:.5rem">'+q.opts.map((o,i)=>'<button onclick="ansQ('+i+')" style="text-align:left;padding:.7rem 1rem;background:var(--bg-card);border:1px solid var(--border);border-radius:8px;cursor:pointer;color:var(--text-primary)">'+o+'</button>').join('')+'</div>';}
function ansQ(i){const q=QQ[qi];const ok=i===q.a;if(ok)qs++;document.getElementById('quiz-container').innerHTML='<div style="padding:1.5rem;background:'+(ok?'rgba(0,200,100,.08)':'rgba(255,60,60,.08)')+';border:1px solid '+(ok?'#00c864':'#ff3c3c')+';border-radius:12px;margin-bottom:1rem"><div style="font-size:1.4rem;margin-bottom:.5rem">'+(ok?'✅ Correct!':'❌ Not quite')+'</div><p style="font-size:.9rem;line-height:1.6">'+q.e+'</p></div><button onclick="nxtQ()" style="padding:.6rem 1.5rem;background:var(--accent);color:#fff;border:none;border-radius:8px;cursor:pointer">Next →</button>';}
function nxtQ(){qi++;renderQ();}
document.addEventListener('DOMContentLoaded',()=>{updateAllTokenDisplays();initHamburger();initPlaylist();initQuiz();});
